AllCops:
    NewCops: enable
    TargetRubyVersion: 2.6
    Exclude:
        - 'test/**/*'
        - 'vendor/**/*'

Naming/FileName:
    Enabled: false

Style/Documentation:
    Enabled: false

Style/StringLiterals:
    Enabled: true
    EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
    Enabled: true
    EnforcedStyle: double_quotes

Layout/LineLength:
    Max: 120

Metrics/AbcSize:
    Exclude:
        - 'lib/rails-mermaid_erd_markdown/configuration.rb'
        - 'lib/rails-mermaid_erd_markdown/source_data.rb'
        - 'lib/rails-mermaid_erd_markdown/generator.rb'

Metrics/ClassLength:
    Max: 125

Metrics/MethodLength:
    Max: 25
    Exclude:
        - 'lib/rails-mermaid_erd_markdown/configuration.rb'
